name: Generar Consejo Diario

on:
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub UI
  schedule:
    - cron: '0 6 * * *' # Se ejecuta todos los días a las 6:00 AM UTC (ajusta la zona horaria si es necesario)

jobs:
  generate_and_update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del Repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Puedes especificar una versión específica como '3.9' o '3.10'

    - name: Instalar Dependencias
      run: pip install google-generativeai # Instala la biblioteca de Gemini

    - name: Generar y Guardar el Consejo
      run: python generate_daily_advice.py
      env:
        # Aquí pasamos tu API Key de Gemini de forma segura
        # Debes configurar GEMINI_API_KEY en los Secrets de tu repositorio GitHub
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    - name: Configurar Git para el Commit
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Realizar Commit y Push del Consejo Actualizado
      run: |
        git add daily_advice.json # O 'data/daily_advice.json' si está en una subcarpeta
        git commit -m "Automatizado: Actualización del Consejo del Día" || echo "No hay cambios para commit"
        git push
      env:
        # Esto es necesario para que la acción tenga permisos para hacer push
        # La variable GITHUB_TOKEN se genera automáticamente por GitHub
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}Enter file contents here
