name: Generar Consejo Diario

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  generate_and_update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del Repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Instalar Dependencias
      run: pip install google-generativeai

    - name: Generar y Guardar el Consejo
      run: python generate_daily_advice.py
      working-directory: ${{ github.workspace }}
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    - name: Configurar Git para el Commit
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Realizar Commit y Push del Consejo Actualizado
      run: |
        git add daily_advice.json
        git commit -m "Automatizado: Actualización del Consejo del Día" || echo "No hay cambios para commit"
        git push
      working-directory: ${{ github.workspace }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
